spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/denjos/configServer.git
          timeout: 10
          username: denjos
          password: Sa10011*
server:
 port: 8888